name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.2.1
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
      - name: Run tests
        run: make test
